# Generated by Django 5.0.4 on 2024-05-06 14:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_alter_customuser_aadhar_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='aadhar_number',
            field=models.CharField(max_length=12, validators=[django.core.validators.MinLengthValidator(12)]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='mobile',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='pan_number',
            field=models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(null=True, upload_to='user_photos/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='pincode',
            field=models.CharField(max_length=10),
        ),
    ]
